HRM.WebMVCApp/Controllers/InterviewTypeController.cs
using HRM.ApplicationCore.Contract.Service;
using HRM.ApplicationCore.Model.Request;
using HRM.Infrastructure.Service;
using Microsoft.AspNetCore.Mvc;

namespace HRM.WebMVCApp.Controllers
{
    public class InterviewTypeController : Controller
    {
        private readonly IInterviewTypeServiceAsync interviewTypeServiceAsync;

        public InterviewTypeController(IInterviewTypeServiceAsync _interviewTypeServiceAsync)
        {
            interviewTypeServiceAsync = _interviewTypeServiceAsync;
        }
        public async Task<IActionResult> Index()
        {
            var interviewTypeCollection = await interviewTypeServiceAsync.GetAllInterviewTypesAsync();
            return View(interviewTypeCollection);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(InterviewTypeRequestModel model)
        {
            if (ModelState.IsValid)
            {
                await interviewTypeServiceAsync.AddInterviewTypeAsync(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            var result = await interviewTypeServiceAsync.GetInterviewTypeByIdAsnc(id);
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(InterviewTypeRequestModel model)
        {
            try
            {
                await interviewTypeServiceAsync.UpdateInterviewTypeAsync(model);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View(model);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await interviewTypeServiceAsync.GetInterviewTypeByIdAsnc(id);
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(InterviewTypeRequestModel model)
        {
            try
            {
                var result = await interviewTypeServiceAsync.DeleteInterviewTypeAsync(model.Id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
            }
            
        }
    }
}

HRM.WebMVCApp/Views/InterviewType/Create.cshtml
@model InterviewTypeRequestModel
<div class="container">
    <form asp-controller="InterviewType" asp-action="Create" method="post">
        <div class="my-5 row col-12">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title"></span>
        </div>
        <div class="my-5 row col-12 form-check">
            <label for="IsActive">IsActive</label>
            <input type="checkbox" class="form-check-input" asp-for="IsActive">
            <span asp-validation-for="IsActive"></span>
        </div>
        <input type="submit" value="Add Interview Type" class="btn btn-primary" />
    </form>
</div>

HRM.WebMVCApp/Views/InterviewType/Delete.cshtml
@model InterviewTypeResponseModel
<div class="container">
    <form asp-controller="InterviewType" asp-action="Delete" method="post">
        <div class="my-5 row col-12">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" disabled />
            <span asp-validation-for="Title"></span>
        </div>
        <div class="my-5 row col-12 form-check">
            <label for="IsActive">IsActive</label>
            <input type="checkbox" class="form-check-input" asp-for="IsActive" disabled>
            <span asp-validation-for="IsActive"></span>
        </div>
        <input type="submit" value="Add Interview Type" class="btn btn-danger" />
    </form>
</div>

HRM.WebMVCApp/Views/InterviewType/Edit.cshtml
@model InterviewTypeResponseModel
<div class="container">
    <form asp-controller="InterviewType" asp-action="Edit" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="my-5 row col-12">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title"></span>
        </div>
        <div class="my-5 row col-12 form-check">
            <label for="IsActive">IsActive</label>
            <input type="checkbox" class="form-check-input" asp-for="IsActive">
            <span asp-validation-for="IsActive"></span>
        </div>
        <input type="submit" value="Update Interview Type" class="btn btn-primary" />
    </form>
</div>

HRM.WebMVCApp/Views/InterviewType/Index.cshtml
@model IEnumerable<InterviewTypeResponseModel>;

<div class="page-header">
    <h1>List of Interview Types</h1>
</div>

<a asp-action="Create" asp-controller="InterviewType">Add New Interview Type</a>

<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Is Active</th>
            <th colspan="2">Options</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var m in Model)
            {
                <tr>
                    <td>@m.Id</td>
                    <td>@m.Title</td>
                    <td>@m.IsActive</td>
                    <td><a asp-action="Edit" asp-controller="InterviewType" asp-route-id="@m.Id">Edit</a></td>
                    <td><a asp-action="Delete" asp-controller="InterviewType" asp-route-id="@m.Id">Delete</a></td>
                </tr>
            }
        }
    </tbody>
</table>