HRM.WebMVCApp/Controllers/EmployeeRoleController.cs
using HRM.ApplicationCore.Contract.Service;
using HRM.ApplicationCore.Model.Request;
using HRM.Infrastructure.Service;
using Microsoft.AspNetCore.Mvc;

namespace HRM.WebMVCApp.Controllers
{
    public class EmployeeRoleController : Controller
    {
        private readonly IEmployeeRoleServiceAsync employeeRoleServiceAsync;

        public EmployeeRoleController(IEmployeeRoleServiceAsync _employeeRoleServiceAsync)
        {
            employeeRoleServiceAsync = _employeeRoleServiceAsync;
        }
        public async Task<IActionResult> Index()
        {
            var employeeRoleCollection = await employeeRoleServiceAsync.GetAllEmployeeRolesAsync();
            return View(employeeRoleCollection);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeeRoleRequestModel model)
        {
            if (ModelState.IsValid)
            {
                await employeeRoleServiceAsync.AddEmployeeRoleAsync(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            var result = await employeeRoleServiceAsync.GetEmployeeRoleByIdAsnc(id);
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EmployeeRoleRequestModel model)
        {
            try
            {
                await employeeRoleServiceAsync.UpdateEmployeeRoleAsync(model);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View(model);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await employeeRoleServiceAsync.GetEmployeeRoleByIdAsnc(id);
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EmployeeRoleRequestModel model)
        {
            try
            {
                var result = await employeeRoleServiceAsync.DeleteEmployeeRoleAsync(model.Id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
            }
            
        }
    }
}

HRM.WebMVCApp/Views/EmployeeRole/Create.cshtml
@model EmployeeRoleRequestModel
<div class="container">
    <form asp-controller="EmployeeRole" asp-action="Create" method="post">
        <div class="my-5 row col-12">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title"></span>
        </div>
        <div class="my-5 row col-12">
            <label for="Description">Description</label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description"></span>
        </div>
        <div class="my-5 row col-12 form-check">
            <label for="IsActive">IsActive</label>
            <input type="checkbox" class="form-check-input" asp-for="IsActive">
            <span asp-validation-for="IsActive"></span>
        </div>
        <input type="submit" value="Add Employee Role" class="btn btn-primary" />
    </form>
</div>

HRM.WebMVCApp/Views/EmployeeRole/Delete.cshtml
@model EmployeeRoleResponseModel
<div class="container">
    <form asp-controller="EmployeeRole" asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="my-5 row col-12">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" disabled />
            <span asp-validation-for="Title"></span>
        </div>
        <div class="my-5 row col-12">
            <label for="Description">Description</label>
            <input asp-for="Description" class="form-control" disabled />
            <span asp-validation-for="Description"></span>
        </div>
        <div class="my-5 row col-12 form-check">
            <label for="IsActive">IsActive</label>
            <input type="checkbox" class="form-check-input" asp-for="IsActive" disabled>
            <span asp-validation-for="IsActive"></span>
        </div>
        <input type="submit" value="Delete Employ Role" class="btn btn-danger" />
    </form>
</div>

HRM.WebMVCApp/Views/EmployeeRole/Edit.cshtml
@model EmployeeRoleResponseModel
<div class="container">
    <form asp-controller="EmployeeRole" asp-action="Edit" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="my-5 row col-12">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title"></span>
        </div>
        <div class="my-5 row col-12">
            <label for="Description">Description</label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description"></span>
        </div>
        <div class="my-5 row col-12 form-check">
            <label for="IsActive">IsActive</label>
            <input type="checkbox" class="form-check-input" asp-for="IsActive">
            <span asp-validation-for="IsActive"></span>
        </div>
        <input type="submit" value="Update Employ Role" class="btn btn-primary" />
    </form>
</div>

HRM.WebMVCApp/Views/EmployeeRole/Index.cshtml
@model IEnumerable<EmployeeRoleResponseModel>;

<div class="page-header">
    <h1>List of Employee Roles</h1>
</div>

<a asp-action="Create" asp-controller="EmployeeRole">Add New Employee Role</a>

<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Description</th>
            <th>Is Active</th>
            <th colspan="2">Options</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var m in Model)
            {
                <tr>
                    <td>@m.Id</td>
                    <td>@m.Title</td>
                    <td>@m.Description</td>
                    <td>@m.IsActive</td>
                    <td><a asp-action="Edit" asp-controller="EmployeeRole" asp-route-id="@m.Id">Edit</a></td>
                    <td><a asp-action="Delete" asp-controller="EmployeeRole" asp-route-id="@m.Id">Delete</a></td>
                </tr>
            }
        }
    </tbody>
</table>