HRM.WebMVCApp/Controllers/JobRequirementController.cs
using HRM.ApplicationCore.Contract.Service;
using HRM.ApplicationCore.Model.Request;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HRM.WebMVCApp.Controllers
{
    public class JobRequirementController : Controller
    {
        private readonly IJobRequirementServiceAsync jobRequirementServiceAsync;
        private readonly IJobCategoryServiceAsync jobCategoryServiceAsync;

        public JobRequirementController(IJobRequirementServiceAsync _jobRequirementServiceAsync, IJobCategoryServiceAsync _jobCategoryServiceAsync)
        {
            jobRequirementServiceAsync = _jobRequirementServiceAsync;
            jobCategoryServiceAsync = _jobCategoryServiceAsync;
        }
        public async Task<IActionResult> Index()
        {
            var jobRequirementCollection = await jobRequirementServiceAsync.GetAllJobRequirementsAsync();
            return View(jobRequirementCollection);
        }

        public async Task<IActionResult> Create()
        {
            await GetJobCategory();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(JobRequirementRequestModel model)
        {
            if (ModelState.IsValid)
            {
                await jobRequirementServiceAsync.AddJobRequirementAsync(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            var result = await jobRequirementServiceAsync.GetJobRequirementByIdAsnc(id);
            await GetJobCategory();
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(JobRequirementRequestModel model)
        {
            try
            {
                await jobRequirementServiceAsync.UpdateJobRequirementAsync(model);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await jobRequirementServiceAsync.GetJobRequirementByIdAsnc(id);
            await GetJobCategory();
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(JobRequirementRequestModel model)
        {
            try
            {
                var result = await jobRequirementServiceAsync.DeleteJobRequirementAsync(model.Id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
            }

        }

        [NonAction]
        public async Task GetJobCategory()
        {
            ViewBag.JobCategoryList = new SelectList(await jobCategoryServiceAsync.GetAllJobCategorysAsync(), "Id", "Name");
        }
    }
}

HRM.WebMVCApp/Views/JobRequirement/Create.cshtml
@model JobRequirementRequestModel
<div class="container">
    <form asp-controller="JobRequirement" asp-action="Create" method="post">
        <div class="my-5 row col-12">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title"></span>
        </div>
        <div class="my-5 row col-12">
            <label for="Description">Description</label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description"></span>
        </div>
        <div class="my-5 row col-12">
            <label for="TotalPositions">TotalPositions</label>
            <input asp-for="TotalPositions" class="form-control" />
            <span asp-validation-for="TotalPositions"></span>
        </div>
        <div class="my-5 row col-12 input-group date" data-provide="datepicker">
            <label for="PostingDate">PostingDate</label>
            <input asp-for="PostingDate" class="form-control" />
            <span asp-validation-for="PostingDate"></span>
        </div>
        <div class="my-5 row col-12 input-group date" data-provide="datepicker">
            <label for="ClosingDate">ClosingDate</label>
            <input asp-for="ClosingDate" class="form-control" />
            <span asp-validation-for="ClosingDate"></span>
        </div>
        <div class="my-5 row col-12">
            <label for="JobCategoryId">JobCategoryId</label>
            <select asp-for="JobCategoryId" class="form-control">
                @foreach (var item in ViewBag.JobCategoryList)
                {
                        <option value="@item.Value">@item.Text</option>
                }
            </select>
            <span asp-validation-for="JobCategoryId"></span>
        </div>
        <div class="my-5 row col-12 form-check">
            <label for="IsActive">IsActive</label>
            <input type="checkbox" class="form-check-input" asp-for="IsActive">
            <span asp-validation-for="IsActive"></span>
        </div>
        <input type="submit" value="Add Job Requirement" class="btn btn-primary" />
    </form>
</div>

HRM.WebMVCApp/Views/JobRequirement/Delete.cshtml
@model JobRequirementResponseModel
<div class="container">
    <form asp-controller="JobRequirement" asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="my-5 row col-12">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" disabled />
            <span asp-validation-for="Title"></span>
        </div>
        <div class="my-5 row col-12">
            <label for="Description">Description</label>
            <input asp-for="Description" class="form-control" disabled />
            <span asp-validation-for="Description"></span>
        </div>
        <div class="my-5 row col-12">
            <label for="TotalPositions">TotalPositions</label>
            <input asp-for="TotalPositions" class="form-control" disabled />
            <span asp-validation-for="TotalPositions"></span>
        </div>
        <div class="my-5 row col-12 input-group date" data-provide="datepicker">
            <label for="PostingDate">PostingDate</label>
            <input asp-for="PostingDate" class="form-control" disabled />
            <span asp-validation-for="PostingDate"></span>
        </div>
        <div class="my-5 row col-12 input-group date" data-provide="datepicker">
            <label for="ClosingDate">ClosingDate</label>
            <input asp-for="ClosingDate" class="form-control" disabled />
            <span asp-validation-for="ClosingDate"></span>
        </div>
        <div class="my-5 row col-12">
            <label for="JobCategoryId">JobCategoryId</label>
            <select asp-for="JobCategoryId" class="form-control" disabled>
                @foreach (var item in ViewBag.JobCategoryList)
                {
                    <option value="@item.Value">@item.Text</option>
                }
            </select>
            <span asp-validation-for="JobCategoryId"></span>
        </div>
        <div class="my-5 row col-12 form-check">
            <label for="IsActive">IsActive</label>
            <input type="checkbox" class="form-check-input" asp-for="IsActive" disabled>
            <span asp-validation-for="IsActive"></span>
        </div>
        <input type="submit" value="Delete Job Requirement" class="btn btn-danger" />
    </form>
</div>

HRM.WebMVCApp/Views/JobRequirement/Edit.cshtml
@model JobRequirementResponseModel
<div class="container">
    <form asp-controller="JobRequirement" asp-action="Edit" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="my-5 row col-12">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title"></span>
        </div>
        <div class="my-5 row col-12">
            <label for="Description">Description</label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description"></span>
        </div>
        <div class="my-5 row col-12">
            <label for="TotalPositions">TotalPositions</label>
            <input asp-for="TotalPositions" class="form-control" />
            <span asp-validation-for="TotalPositions"></span>
        </div>
        <div class="my-5 row col-12 input-group date" data-provide="datepicker">
            <label for="PostingDate">PostingDate</label>
            <input asp-for="PostingDate" class="form-control" />
            <span asp-validation-for="PostingDate"></span>
        </div>
        <div class="my-5 row col-12 input-group date" data-provide="datepicker">
            <label for="ClosingDate">ClosingDate</label>
            <input asp-for="ClosingDate" class="form-control" />
            <span asp-validation-for="ClosingDate"></span>
        </div>
        <div class="my-5 row col-12">
            <label for="JobCategoryId">JobCategoryId</label>
            <select asp-for="JobCategoryId" class="form-control">
                @foreach (var item in ViewBag.JobCategoryList)
                {
                    <option value="@item.Value">@item.Text</option>
                }
            </select>
            <span asp-validation-for="JobCategoryId"></span>
        </div>
        <div class="my-5 row col-12 form-check">
            <label for="IsActive">IsActive</label>
            <input type="checkbox" class="form-check-input" asp-for="IsActive">
            <span asp-validation-for="IsActive"></span>
        </div>
        <input type="submit" value="Update Job Requirement" class="btn btn-primary" />
    </form>
</div>

HRM.WebMVCApp/Views/JobRequirement/Index.cshtml
@model IEnumerable<JobRequirementResponseModel>;

<div class="page-header">
    <h1>List of Employees</h1>
</div>

<a asp-action="Create" asp-controller="JobRequirement">Add New Job Requirement</a>

<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th># of Total Positions</th>
            <th>Posting Date</th>
            <th>Closing Date</th>
            <th>Job Category Id</th>
            <th>Is Active</th>
            <th colspan="2">Options</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var m in Model)
            {
                <tr>
                    <td>@m.Title</td>
                    <td>@m.Description</td>
                    <td>@m.TotalPositions</td>
                    <td>@m.PostingDate</td>
                    <td>@m.ClosingDate</td>
                    <td>@m.JobCategoryId</td>
                    <td>@m.IsActive</td>
                    <td><a asp-action="Edit" asp-controller="JobRequirement" asp-route-id="@m.Id">Edit</a></td>
                    <td><a asp-action="Delete" asp-controller="JobRequirement" asp-route-id="@m.Id">Delete</a></td>
                </tr>
            }
        }
    </tbody>
</table>